#!/usr/bin/env python3
"""Compile public UTF-8 prompt defaults into Swift; --check detects stale generated code."""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
FILES = {
    "fullRewrite": "full-rewrite.txt",
    "lightCleanup": "light-cleanup.txt",
    "punctuation": "punctuation.txt",
    "rewriteVerifier": "rewrite-verifier.txt",
}
OUTPUT = ROOT / "Sources/FnDictate/PublicPromptDefaults.swift"


def generated():
    lines = ["// Generated by scripts/generate-prompts.py from prompts/*.txt. Do not edit directly.",
             "// The files are compiled into the signed app; no remote prompt is fetched at runtime.",
             "enum PublicPromptDefaults {"]
    for name, filename in FILES.items():
        text = (ROOT / "prompts" / filename).read_text(encoding="utf-8").strip()
        if not text:
            raise ValueError(f"Empty prompt: {filename}")
        # Choose a raw string delimiter that cannot terminate or interpolate the input.
        hashes = "#"
        while '"""' + hashes in text or "\\" + hashes + "(" in text:
            hashes += "#"
        lines.append(f'    static let {name} = {hashes}"""')
        lines.extend("    " + line for line in text.splitlines())
        lines.append(f'    """{hashes}')
    lines.extend(["}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("Prompt defaults are stale. Run python3 scripts/generate-prompts.py", file=sys.stderr)
            return 1
        print("Public prompt defaults match their compiled Swift constants.")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
